development: &development
  developer: false
  base: "http://localhost:3000"
  return_to: "http://localhost:3000/"
  email: jrochelly@gmail.com

test:
  <<: *development

production:
  authenticity_token: 9CA8D46AF0C6177CB4C23D76CAF5E4B0
  email: jrochelly@gmail.com
  return_to: "http://achacasas.com/confirmacao_de_pagamento"

